Vagrant.configure(2) do |config|
    config.vm.define "nfs-server" do |subconfig|
        subconfig.vm.box = "centos/8"
        subconfig.vm.hostname="nfs-server"
        subconfig.vm.network :private_network, ip: "192.168.50.12"
        subconfig.vm.provider "virtualbox" do |vb|
            vb.memory = "1024"
            vb.cpus = "1"
        subconfig.vm.provision "shell", path: "nfs-server.sh"
        end
    end

    config.vm.define "nfs-client" do |subconfig|
        subconfig.vm.box = "centos/8"
        subconfig.vm.hostname="nfs-client"
        subconfig.vm.network :private_network, ip: "192.168.50.13"
        subconfig.vm.provider "virtualbox" do |vb|
            vb.memory = "1024"
            vb.cpus = "1"
        subconfig.vm.provision "shell", path: "nfs-client.sh"
        end
    end
    config.ssh.insert_key = false
    config.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key', '~/.ssh/id_rsa']
    config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"   
end